language: rust
rust:
  - stable
branches:
  only:
    - master
script:
  - cd musig
  - cargo test --release
  - cd ../bls
  - cargo test --release
  - cd ../ps
  - cargo test --release --no-default-features --features G2G1
  - cargo test --release --no-default-features --features G1G2
  - cd ../delg_cred_cdd
    - cargo test --release
    - cargo test --release