[package]
name = "multi-sigs"
version = "0.1.0"
authors = ["Lovesh Harchandani <lovesh.bond@gmail.com>"]
description = "Various signature schemes. BLS."
license = "MIT/Apache-2.0"

[dependencies]
rand = "0.5.3"
lazy_static = "1.0"
log = "*"

[dependencies.amcl]
path = "./amcl"
